# Generated by Django 5.2.5 on 2025-11-15 22:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmacia', '0002_initial'),
        ('motorista', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoMovimiento',
            fields=[
                ('codigo_estado', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estado de Movimiento',
                'verbose_name_plural': 'Estados de Movimiento',
                'db_table': 'ESTADOS_MOVIMIENTO',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('idMovimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipoMovimiento', models.CharField(choices=[('directo', 'Directo'), ('receta', 'Receta'), ('traslado', 'Traslado'), ('reenvio', 'Reenvío')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_camino', 'En Camino'), ('entregado', 'Entregado'), ('fallido', 'Fallido'), ('anulado', 'Anulado'), ('pendiente_autorizacion', 'Pendiente Autorización')], default='pendiente', max_length=30)),
                ('fechaCreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fechaEntrega', models.DateTimeField(blank=True, null=True)),
                ('direccionDestino', models.CharField(blank=True, max_length=100, null=True)),
                ('clienteNombre', models.CharField(blank=True, max_length=100, null=True)),
                ('clienteTelefono', models.CharField(blank=True, max_length=20, null=True)),
                ('requiereReceta', models.BooleanField(default=False)),
                ('recetaRetirada', models.BooleanField(default=False)),
                ('metodoPago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('pos', 'POS')], max_length=10, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('requiereAutorizacion', models.BooleanField(default=False)),
                ('fechaAutorizacion', models.DateTimeField(blank=True, null=True)),
                ('autorizadoPor', models.ForeignKey(blank=True, db_column='autorizadoPor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_autorizados', to=settings.AUTH_USER_MODEL)),
                ('idFarmaciaDestino', models.ForeignKey(blank=True, db_column='idFarmaciaDestino', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_destino', to='farmacia.farmacia')),
                ('idFarmaciaOrigen', models.ForeignKey(db_column='idFarmaciaOrigen', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_origen', to='farmacia.farmacia')),
                ('movimientoOrigen', models.ForeignKey(blank=True, db_column='movimientoOrigen', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reenvios_posteriores', to='movimiento.movimiento')),
                ('rutMotorista', models.ForeignKey(db_column='rutMotorista', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='motorista.motorista')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'db_table': 'MOVIMIENTO',
            },
        ),
        migrations.CreateModel(
            name='MovimientoDirecto',
            fields=[
                ('movimiento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='directo', serialize=False, to='movimiento.movimiento')),
                ('direccionEntrega', models.CharField(max_length=255)),
                ('comunaEntrega', models.CharField(max_length=100)),
                ('telefonoCliente', models.CharField(max_length=20)),
                ('producto', models.CharField(max_length=255)),
                ('instrucciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Movimiento Directo',
                'verbose_name_plural': 'Movimientos Directos',
                'db_table': 'MOVIMIENTO_DIRECTO',
            },
        ),
        migrations.CreateModel(
            name='MovimientoReceta',
            fields=[
                ('movimiento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='receta', serialize=False, to='movimiento.movimiento')),
                ('direccionEntrega', models.CharField(max_length=255)),
                ('comunaEntrega', models.CharField(max_length=100)),
                ('telefonoCliente', models.CharField(max_length=20)),
                ('producto', models.CharField(max_length=255)),
                ('archivoReceta', models.FileField(blank=True, null=True, upload_to='recetas/')),
                ('requiereRetiroReceta', models.BooleanField(default=False)),
                ('recetaRetirada', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Movimiento Receta',
                'verbose_name_plural': 'Movimientos Receta',
                'db_table': 'MOVIMIENTO_RECETA',
            },
        ),
        migrations.CreateModel(
            name='MovimientoTraslado',
            fields=[
                ('movimiento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='traslado', serialize=False, to='movimiento.movimiento')),
                ('producto', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField()),
                ('motivoTraslado', models.CharField(max_length=255)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Movimiento Traslado',
                'verbose_name_plural': 'Movimientos Traslado',
                'db_table': 'MOVIMIENTO_TRASLADO',
            },
        ),
        migrations.CreateModel(
            name='BitacoraMovimiento',
            fields=[
                ('idBitacora', models.AutoField(primary_key=True, serialize=False)),
                ('fechaCambio', models.DateTimeField(default=django.utils.timezone.now)),
                ('estadoAnterior', models.CharField(max_length=50)),
                ('estadoNuevo', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_bitacora', to=settings.AUTH_USER_MODEL)),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora', to='movimiento.movimiento')),
            ],
            options={
                'verbose_name': 'Bitácora de Movimiento',
                'verbose_name_plural': 'Bitácoras de Movimiento',
                'db_table': 'BITACORA_MOVIMIENTO',
            },
        ),
        migrations.CreateModel(
            name='MovimientoReenvio',
            fields=[
                ('movimiento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='reenvio', serialize=False, to='movimiento.movimiento')),
                ('motivoReenvio', models.CharField(max_length=255)),
                ('nuevaDireccion', models.CharField(max_length=255)),
                ('nuevaFecha', models.DateTimeField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('movimientoOriginal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reenvios', to='movimiento.movimiento')),
            ],
            options={
                'verbose_name': 'Movimiento Reenvío',
                'verbose_name_plural': 'Movimientos Reenvío',
                'db_table': 'MOVIMIENTO_REENVIO',
            },
        ),
    ]
