# Generated by Django 5.2.7 on 2025-11-29 14:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento', '0002_movimiento_creado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenDespacho',
            fields=[
                ('idOrden', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_orden', models.CharField(max_length=20, unique=True, verbose_name='Número de Orden')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('parcialmente_entregado', 'Parcialmente Entregado'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=30)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_compra_online', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Compra Online')),
                ('cliente_nombre', models.CharField(max_length=100)),
                ('cliente_telefono', models.CharField(max_length=20)),
                ('cliente_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion_entrega', models.CharField(max_length=255)),
                ('comuna_entrega', models.CharField(max_length=100)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('online', 'Online')], max_length=20)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Orden de Despacho',
                'verbose_name_plural': 'Órdenes de Despacho',
                'db_table': 'ORDEN_DESPACHO',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.DeleteModel(
            name='EstadoMovimiento',
        ),
        migrations.AlterModelOptions(
            name='movimiento',
            options={'ordering': ['-fechaCreacion'], 'verbose_name': 'Movimiento', 'verbose_name_plural': 'Movimientos'},
        ),
        migrations.AddField(
            model_name='movimiento',
            name='cantidad',
            field=models.IntegerField(default=1, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='intentos_entrega',
            field=models.IntegerField(default=0, verbose_name='Intentos de Entrega'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='prioridad',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Alta'), (3, 'Urgente')], default=1),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='producto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Producto(s)'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='orden_despacho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='movimiento.ordendespacho', verbose_name='Orden de Despacho'),
        ),
    ]
