# Generated by Django 5.2.7 on 2025-11-15 19:23

import apps.moto.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('patente', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[apps.moto.models.validar_patente_chilena], verbose_name='Patente')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2099)], verbose_name='Año')),
                ('color', models.CharField(max_length=30)),
                ('numChasis', models.CharField(max_length=50, unique=True, verbose_name='Número de Chasis')),
                ('motor', models.CharField(max_length=50, unique=True, verbose_name='Número de Motor')),
                ('propietario', models.CharField(choices=[('EMPRESA', 'Empresa'), ('MOTORISTA', 'Motorista')], max_length=50)),
                ('permisoCirculacion', models.FileField(upload_to='documentos/motos/permisos/', verbose_name='Permiso de Circulación')),
                ('seguro', models.FileField(upload_to='documentos/motos/seguros/', verbose_name='Póliza de Seguro')),
                ('revisionTecnica', models.FileField(upload_to='documentos/motos/revisiones/', verbose_name='Revisión Técnica')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Moto',
                'verbose_name_plural': 'Motos',
                'db_table': 'moto',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
