"""
Django settings for LogiCo_ project.

Generated by 'django-admin startproject' using Django 5.2.5.
"""

import os
import sys
from pathlib import Path
from django.utils.timezone import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Añadir la carpeta apps al path de Python
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# Configuración de MySQL
try:
    import pymysql
    pymysql.install_as_MySQLdb()
except ImportError:
    pass

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-your-secret-key-here-change-in-production'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
TESTING = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'crispy_forms',
    'crispy_bootstrap5',
    
   # Local apps 
    'apps.core',
    'apps.usuario',
    'apps.farmacia',
    'apps.motorista',
    'apps.moto',
    'apps.asignacion',
    'apps.movimiento',
    'apps.reporte',
    'apps.configuracion',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.AuditoriaMiddleware',
]

ROOT_URLCONF = 'LogiCo_.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.datos_globales',
            ],
        },
    },
]

WSGI_APPLICATION = 'LogiCo_.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  
        'NAME': BASE_DIR / 'db.sqlite3',       
    }
}

# Custom User Model
AUTH_USER_MODEL = 'usuario.Usuario'

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'es-cl'
TIME_ZONE = 'America/Santiago'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Configuración de login
LOGIN_URL = 'usuario:login'
LOGIN_REDIRECT_URL = 'usuario:dashboard'
LOGOUT_REDIRECT_URL = 'usuario:login'

# CONFIGURACION DE SESIONES

# Tiempo de vida de la sesion en segundos (1 hora de inactividad)
SESSION_COOKIE_AGE = 3600
# La sesion expira al cerrar el navegador
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# Solo enviar cookies de sesion por HTTPS (False en desarrollo, True en produccion)
SESSION_COOKIE_SECURE = False
# Proteccion contra acceso via JavaScript
SESSION_COOKIE_HTTPONLY = True
# Nombre personalizado de la cookie de sesion
SESSION_COOKIE_NAME = 'sistematbc_sessionid'
# Motor de almacenamiento de sesiones (base de datos)
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
# Guardar sesion en cada request para actualizar timeout
SESSION_SAVE_EVERY_REQUEST = True

# CONFIGURACION DE SEGURIDAD CSRF

# Solo enviar cookies CSRF por HTTPS (False en desarrollo, True en produccion)
CSRF_COOKIE_SECURE = False
# Permitir acceso a cookie CSRF via JavaScript (necesario para AJAX)
CSRF_COOKIE_HTTPONLY = False
# Politica SameSite para cookies CSRF
CSRF_COOKIE_SAMESITE = 'Lax'
# No usar sesiones para almacenar tokens CSRF
CSRF_USE_SESSIONS = False
# Vista personalizada para fallos CSRF
CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure'

# HEADERS DE SEGURIDAD

# Filtro XSS para navegadores compatibles
SECURE_BROWSER_XSS_FILTER = True
# Prevenir sniffing de tipo MIME
SECURE_CONTENT_TYPE_NOSNIFF = True
# Proteccion contra clickjacking
X_FRAME_OPTIONS = 'DENY'

# Email configuration (para recuperación de contraseñas)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@logico.com'

# Configuración específica para pruebas de seguridad
SECURITY_CONFIG = {
    'MAX_LOGIN_ATTEMPTS': 5,
    'LOCKOUT_TIME': 900,  # 15 minutos
    'SESSION_TIMEOUT': 1200,  # 20 minutos
    'PASSWORD_MIN_LENGTH': 8,
    'ALLOWED_FILE_TYPES': ['.pdf', '.jpg', '.jpeg', '.png'],
    'MAX_FILE_SIZE': 10 * 1024 * 1024,  # 10MB
}