# Generated by Django 5.2.7 on 2025-11-18 20:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmacia', '0002_initial'),
        ('movimiento', '0002_movimiento_creado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoIncidencia',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('gravedad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=20, verbose_name='Nivel de Gravedad')),
                ('requiere_autorizacion', models.BooleanField(default=False, verbose_name='Requiere Autorización')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Incidencia',
                'verbose_name_plural': 'Tipos de Incidencia',
                'db_table': 'configuracion_tipo_incidencia',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('clave', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Clave')),
                ('valor', models.TextField(verbose_name='Valor')),
                ('tipo', models.CharField(choices=[('TEXTO', 'Texto'), ('NUMERO', 'Número'), ('BOOLEANO', 'Booleano'), ('JSON', 'JSON')], default='TEXTO', max_length=20, verbose_name='Tipo de Dato')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('editable', models.BooleanField(default=True, verbose_name='Editable')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
                'db_table': 'configuracion_sistema',
            },
        ),
        migrations.CreateModel(
            name='RangoAccion',
            fields=[
                ('farmacia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rango_accion', serialize=False, to='farmacia.farmacia', verbose_name='Farmacia')),
                ('distancia_maxima_km', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Distancia Máxima (km)')),
                ('comunas_permitidas', models.TextField(blank=True, help_text='Lista de comunas separadas por coma donde puede operar el motorista', null=True, verbose_name='Comunas Permitidas')),
                ('horario_inicio', models.TimeField(default='08:00', verbose_name='Horario Inicio')),
                ('horario_fin', models.TimeField(default='22:00', verbose_name='Horario Fin')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rangos_accion_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rangos_accion_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rango de Acción',
                'verbose_name_plural': 'Rangos de Acción',
                'db_table': 'configuracion_rango_accion',
            },
        ),
        migrations.CreateModel(
            name='IncidenciaMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('REGISTRADA', 'Registrada'), ('EN_REVISION', 'En Revisión'), ('RESUELTA', 'Resuelta'), ('ESCALADA', 'Escalada'), ('CERRADA', 'Cerrada')], default='REGISTRADA', max_length=20, verbose_name='Estado')),
                ('descripcion', models.TextField(verbose_name='Descripción de la Incidencia')),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='incidencias/evidencias/', verbose_name='Evidencia')),
                ('fecha_incidencia', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Incidencia')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('resolucion', models.TextField(blank=True, null=True, verbose_name='Resolución')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('asignada_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Asignada a')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='movimiento.movimiento', verbose_name='Movimiento')),
                ('reportada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_reportadas', to=settings.AUTH_USER_MODEL, verbose_name='Reportada por')),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_resueltas', to=settings.AUTH_USER_MODEL, verbose_name='Resuelta por')),
                ('tipo_incidencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.tipoincidencia', verbose_name='Tipo de Incidencia')),
            ],
            options={
                'verbose_name': 'Incidencia de Movimiento',
                'verbose_name_plural': 'Incidencias de Movimiento',
                'db_table': 'configuracion_incidencia_movimiento',
                'ordering': ['-fecha_incidencia'],
            },
        ),
    ]
