# Generated by Django 5.2.7 on 2025-11-15 19:23

import apps.motorista.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, validators=[apps.motorista.models.validar_rut_chileno], verbose_name='RUT')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellidoPaterno', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('apellidoMaterno', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('comuna', models.CharField(max_length=50, verbose_name='Comuna')),
                ('provincia', models.CharField(max_length=50, verbose_name='Provincia')),
                ('region', models.CharField(max_length=50, verbose_name='Región')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('moto', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, verbose_name='¿Tiene Moto?')),
                ('archivo', models.FileField(upload_to='licencias/', verbose_name='Licencia de Conductor')),
                ('fechaUltControl', models.DateField(verbose_name='Fecha Último Control')),
                ('fechaControl', models.DateField(verbose_name='Fecha Próximo Control')),
                ('fechaVencimiento', models.DateField(verbose_name='Fecha Vencimiento Licencia')),
                ('parentesco', models.CharField(choices=[('PADRE', 'Padre'), ('MADRE', 'Madre'), ('HERMANO', 'Hermano'), ('HERMANA', 'Hermana'), ('TIO', 'Tío'), ('TIA', 'Tía'), ('PRIMO', 'Primo'), ('PRIMA', 'Prima'), ('AMIGO', 'Amigo'), ('AMIGA', 'Amiga'), ('OTRO', 'Otro')], max_length=50, verbose_name='Parentesco Contacto')),
                ('telefonoEmergencia', models.CharField(max_length=15, verbose_name='Teléfono Emergencia')),
                ('nombreContacto', models.CharField(default='N/A', max_length=100, verbose_name='Nombre Contacto')),
                ('apellidoContacto', models.CharField(default='N/A', max_length=100, verbose_name='Apellido Contacto')),
                ('direccionContacto', models.CharField(default='N/A', max_length=200, verbose_name='Dirección Contacto')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
                'db_table': 'motorista',
                'ordering': ['apellidoPaterno', 'nombre'],
            },
        ),
    ]
