# Generated by Django 5.2.7 on 2025-11-18 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_reporte', models.CharField(choices=[('farmacia', 'Farmacias'), ('motorista', 'Motoristas'), ('moto', 'Motos'), ('asignacion', 'Asignaciones'), ('movimiento', 'Movimientos')], max_length=20)),
                ('formato_salida', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel')], default='pdf', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Configuración de Reporte',
                'verbose_name_plural': 'Configuraciones de Reportes',
                'db_table': 'configuracion_reporte',
            },
        ),
        migrations.CreateModel(
            name='FiltroReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_filtro', models.CharField(max_length=50)),
                ('valor_filtro', models.TextField()),
                ('tipo_filtro', models.CharField(max_length=30)),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporte.configuracionreporte')),
            ],
            options={
                'db_table': 'filtro_reporte',
            },
        ),
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(choices=[('farmacia', 'Farmacias'), ('motorista', 'Motoristas'), ('moto', 'Motos'), ('asignacion', 'Asignaciones'), ('movimiento', 'Movimientos')], max_length=20)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel')], max_length=10)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=15)),
                ('filtros_aplicados', models.JSONField(default=dict)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte Generado',
                'verbose_name_plural': 'Reportes Generados',
                'db_table': 'reporte_generado',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
