# Generated by Django 5.2.7 on 2025-11-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportegenerado',
            options={'ordering': ['-fecha_generacion'], 'permissions': [('view_reporte', 'Puede ver reportes'), ('view_reporte_gerencial', 'Puede ver reportes gerenciales')], 'verbose_name': 'Reporte Generado', 'verbose_name_plural': 'Reportes Generados'},
        ),
        migrations.AlterField(
            model_name='configuracionreporte',
            name='tipo_reporte',
            field=models.CharField(choices=[('farmacia', 'Farmacias'), ('motorista', 'Motoristas'), ('moto', 'Motos'), ('asignacion', 'Asignaciones'), ('movimiento', 'Movimientos'), ('ordenes', 'Órdenes de Despacho')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reportegenerado',
            name='tipo_reporte',
            field=models.CharField(choices=[('farmacia', 'Farmacias'), ('motorista', 'Motoristas'), ('moto', 'Motos'), ('asignacion', 'Asignaciones'), ('movimiento', 'Movimientos'), ('ordenes', 'Órdenes de Despacho')], max_length=20),
        ),
    ]
