# Generated by Django 5.2.7 on 2025-11-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('IdFarmacia', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID Farmacia')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Farmacia')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('comuna', models.CharField(max_length=50, verbose_name='Comuna')),
                ('provincia', models.CharField(max_length=50, verbose_name='Provincia')),
                ('region', models.CharField(max_length=50, verbose_name='Región')),
                ('apertura', models.TimeField(verbose_name='Hora Apertura')),
                ('cierre', models.TimeField(verbose_name='Hora Cierre')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Longitud')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Farmacia',
                'verbose_name_plural': 'Farmacias',
                'db_table': 'farmacia',
                'ordering': ['nombre'],
            },
        ),
    ]
