# Generated by Django 5.2.7 on 2025-11-18 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacionmoto',
            options={'permissions': [('can_manage_asignaciones', 'Puede gestionar asignaciones')]},
        ),
    ]
